language: java

script:
- ./gradlew -i check
- ./gradlew jar
- ./gradlew javadoc
  
 before_install:
   - mysql -e "create database IF NOT EXISTS monopoly;" -uroot

before_script:
  - ./gradlew createDatabase

 jdk:
- oraclejdk7

services:
  - mysql
 
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis-scripts/push-test-results.sh
  
